[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
addopts = --strict-markers --disable-warnings -ra
markers =
    integration: Integration tests
    unit: Unit tests
