# From the latest MySQL image
FROM mysql:5.6

# Set root MySQL password
ENV MYSQL_ROOT_PASSWORD password

# Set (and create) mysql database
ENV MYSQL_DATABASE erms

# Add Schema to docker entrypoint to seed db
ADD src/sql/creation_script.sql /docker-entrypoint-initdb.d
ADD src/sql/insert_statements_script.sql /docker-entrypoint-initdb.d
